cavernadapizza/cadastros/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import ClienteCreateView, ClienteUpdateView, ClienteListView, ClienteDeleteView
from .views import EnderecoCreateView, EnderecoListView
from .views import PedidoCreateView, PedidoListView
from .views import ItensPedidoCreateView
from .views import PizzaListView, PizzaCreateView, PizzaUpdateView, PizzaDeleteView


urlpatterns = [
    path('cliente/create', ClienteCreateView.as_view(), name='cliente_create'),
    path('cliente/<int:pk>/delete', ClienteDeleteView.as_view(), name='cliente_delete'),
    path('cliente/<int:pk>/update', ClienteUpdateView.as_view(), name='cliente_update'),
    path('cliente/list', ClienteListView.as_view(), name='cliente_list'),
    
    path('endereco/create', EnderecoCreateView.as_view(), name='endereco_create'),
    path('endereco/list', EnderecoListView.as_view(), name='endereco_list'),    

    path('pizza/list', PizzaListView.as_view(), name='pizza_list'),
    path('pizza/create', PizzaCreateView.as_view(), name='pizza_create'),
    path('pizza/<int:pk>/update', PizzaUpdateView.as_view(), name='pizza_update'),
    path('pizza/<int:pk>/delete', PizzaDeleteView.as_view(), name='pizza_delete'),
    
    path('pedido/create', PedidoCreateView.as_view(), name='pedido_create'),
    path('pedido/list', PedidoListView.as_view(), name='pedido_list'),
    
    path('itenspedido/create', ItensPedidoCreateView.as_view(), name='itenspedido_create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cavernadapizza/cavernadapizza/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paginas.urls')),
    path('', include('cadastros.urls')),
]

cavernadapizza/paginas/urls.py
from django.urls import path
from . import views

#Importa view que foi criada
from .views import SobreView

urlpatterns = [
#    path('', PaginaView.as_view(), name='index'),
    path('', views.index, name='index'),
    path('sobre/', SobreView.as_view(), name='sobre'),
]

cavernadapizza/cadastros/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Endereco(models.Model):
    #cliente = models.OneToOneField(Cliente, on_delete=models.CASCADE)
    endereco = models.CharField(max_length=200)
    numero = models.IntegerField()
    complemento = models.CharField(max_length=100, blank=True, null=True)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=2)
    cep = models.CharField(max_length=10)

    def __str__(self):
        return self.endereco

class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)
    endereco = models.OneToOneField(Endereco, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Pizza(models.Model):
    nome = models.CharField(max_length=100)
    valor_p = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Valor Pequena')
    valor_m = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Valor Média')
    valor_g = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='Valor Grande')
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    imagem = models.ImageField(upload_to='pizzas/', null=True, blank=True)
    
    def __str__(self):
        return f"{self.nome}"
    
class Pedido(models.Model):
    TIPOS_PAGAMENTO = (
        ('Dinheiro', 'Dinheiro'),
        ('Debito', 'Debito'),
        ('Credito', 'Credito'),
        ('Pix', 'Pix'),        
    )
    data_hora = models.DateTimeField()
    valor_total = models.DecimalField(max_digits=5, decimal_places=2)
    tipo_pagamento = models.CharField(max_length=15, choices=TIPOS_PAGAMENTO)
    cliente = models.ForeignKey("Cliente", on_delete=models.CASCADE, related_name='pedidos')
        
    def __str__(self):
        return f'{self.cliente} - {self.valor_total}'
    
class ItensPedido(models.Model):
    TAMANHO = (
        ('Pequena', 'Pequena'),
        ('Média', 'Média'),
        ('Grande', 'Grande'),
    )
    item_id = models.IntegerField()
    tamanho = models.CharField(max_length=10, choices=TAMANHO)
    quantidade = models.IntegerField()
    preco_unitario = models.DecimalField(max_digits=5, decimal_places=2)
    
    pizza = models.ForeignKey("Pizza", on_delete=models.CASCADE, related_name='ItensPedido')
    pedido = models.ForeignKey("Pedido", on_delete=models.CASCADE, related_name='ItensPedido')
            
    def __str__(self):
        return f'{self.item_id} {self.tamanho} - {self.quantidade} - {self.preco_unitario}, ({self.pedido}'  
   

cavernadapizza/cadastros/forms.py
from django import forms
#from django.contrib.auth.models import User
from .models import Pizza
from .models import Cliente, Endereco, Pedido, ItensPedido

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'email', 'telefone', 'endereco']
        
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)
    
class EnderecoForm(forms.ModelForm):
    class Meta:
        model = Endereco
        fields = ['endereco',
                  'numero',
                  'complemento',
                  'bairro',
                  'cidade',
                  'estado',
                  'cep']

class ClienteEnderecoUpdateForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'email', 'telefone']
        
    endereco = forms.CharField(max_length=200)
    numero = forms.IntegerField()
    complemento = forms.CharField(max_length=100, required=False)
    bairro = forms.CharField(max_length=100)
    cidade = forms.CharField(max_length=100)
    estado = forms.CharField(max_length=2)
    cep = forms.CharField(max_length=10)
    username = forms.CharField(max_length=30, required=False)
    password = forms.CharField(widget=forms.PasswordInput, required=False)

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['nome', 'valor_p', 'valor_m', 'valor_g', 'descricao', 'imagem']
        widgets = {
            'imagem': forms.FileInput(attrs={'accept': 'image/*'}),

        }
        
class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['tipo_pagamento', 'data_hora', 'valor_total', 'cliente']
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['data_hora'].widget = forms.DateTimeInput(attrs={'type': 'datetime-local'})
        
class ItensPedidoForm(forms.ModelForm):
    class Meta:
        model = ItensPedido
        fields = ['item_id', 'tamanho', 'quantidade', 'preco_unitario', 'pedido']
        

cavernadapizza/cadastros/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from .models import Cliente, Endereco, Pizza, Pedido, ItensPedido
from .forms import ClienteForm, PizzaForm, EnderecoForm, ClienteEnderecoUpdateForm, PedidoForm, ItensPedidoForm 
from django.contrib.auth.models import User
# Create your views here.


###################### CREATE ########################### 
class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm
    template_name = 'cadastros/cliente_form.html'
    success_url = reverse_lazy('cliente_list')
        
    def form_valid(self, form):
        user = None
        if 'username' in form.cleaned_data and 'password' in form.cleaned_data:
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )
            
        cliente = form.save(commit=False)
        cliente.user = user
        cliente.save()
        
        return super().form_valid(form)    
    
class EnderecoCreateView(CreateView):
    model = Endereco
    form_class = EnderecoForm
    template_name = 'cadastros/endereco_form.html'
    success_url = reverse_lazy('cliente_create') 

class PizzaCreateView(CreateView):
    model = Pizza
    form_class = PizzaForm
    template_name = 'cadastros/pizza_form.html'

    def get_success_url(self):
        return reverse_lazy('pizza_list')
    
class PedidoCreateView(CreateView):
    model = Pedido
    form_class = PedidoForm
    template_name = 'cadastros/pedido_form.html'
    success_url = reverse_lazy('pedido_list')
    
    def form_valid(self, form):
        form.instance.cliente = self.request.user.cliente
        return super().form_valid(form)
    
class ItensPedidoCreateView(CreateView):
    model = ItensPedido
    form_class = ItensPedidoForm
    template_name = 'cadastros/itenspedido_form.html'
    success_url = reverse_lazy('pedido_list')
    
    def form_valid(self, form):
        form.instance.pedido = Pedido.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

###################### UPDATE ###########################
class ClienteUpdateView(UpdateView):
    model = Cliente
    form_class = ClienteEnderecoUpdateForm
    template_name = 'cadastros/cliente_update_form.html'
    success_url = reverse_lazy('cliente_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cliente = self.object  # Obtém a instância do Cliente atual

        # Preencha os campos do formulário com os dados do Cliente, Endereço e Usuário
        context['form'].initial.update({
            'nome': cliente.nome,
            'email': cliente.email,
            'telefone': cliente.telefone,
            'endereco': cliente.endereco.endereco,
            'numero': cliente.endereco.numero,
            'complemento': cliente.endereco.complemento,
            'bairro': cliente.endereco.bairro,
            'cidade': cliente.endereco.cidade,
            'estado': cliente.endereco.estado,
            'cep': cliente.endereco.cep,
            'username': cliente.user.username,
            'password': ''  # A senha não é preenchida por razões de segurança
        })

        context['form'].fields['password'].required = False

        return context
    
    def form_valid(self, form):
        # Obtenha a instância do cliente atual
        cliente = form.save(commit=False)

        # Atualize as informações do cliente com os dados do formulário
        cliente.nome = form.cleaned_data['nome']
        cliente.email = form.cleaned_data['email']
        cliente.telefone = form.cleaned_data['telefone']
                
        # Obtenha a instância do endereço associado ao cliente
        endereco = cliente.endereco
        endereco.endereco = form.cleaned_data['endereco']
        endereco.numero = form.cleaned_data['numero']
        endereco.complemento = form.cleaned_data['complemento']
        endereco.bairro = form.cleaned_data['bairro']
        endereco.cidade = form.cleaned_data['cidade']
        endereco.estado = form.cleaned_data['estado']
        endereco.cep = form.cleaned_data['cep']
        
        user = cliente.user
        user.username = form.cleaned_data['username']
        
        # Se uma nova senha for fornecida, atualize-a
        password = form.cleaned_data.get('password')
        if password:
            user.set_password(password)
            
        # Salve as alterações
        endereco.save()
        user.save()
        cliente.save()
        
        messages.success(self.request, 'Dados atualizados com sucesso')
        return redirect(self.get_success_url())

class PizzaUpdateView(UpdateView):
    model = Pizza
    form_class = PizzaForm
    template_name = 'cadastros/pizza_form.html'
#    sucess_url = reverse_lazy('pizza_list')
    def get_success_url(self):
        return reverse_lazy('pizza_list')

###################### LISTAR ##########################
class ClienteListView(ListView):
    model = Cliente
    template_name = 'listas/cliente_list.html'
    context_object_name = 'clientes'

class EnderecoListView(ListView):
    model = Endereco    
    template_name = 'listas/endereco_list.html'

class PizzaListView(ListView):
    model = Pizza
    template_name = 'listas/pizza_list.html'
    
class PedidoListView(ListView):
    model = Pedido
    template_name = 'listas/pedido_list.html'
    context_object_name = 'pedidos'
    
class ItensPedidoListView(ListView):
    model = ItensPedido
    template_name = 'listas/pedido_list.html'
    context_object_name = 'itens_pedidos'
    
    def get_queryset(self):
        pedido_id = self.kwargs['pedido_id']
        return ItensPedido.objects.filter(pedido_id=pedido_id)

###################### DELETE ###########################
class ClienteDeleteView(DeleteView):
    model = Cliente
    template_name = 'cadastros/cliente_delete.html'
    #success_url = reverse_lazy('cliente_list')
    
    def get(self, request, pk):
        try:
            cliente = Cliente.objects.get(pk=pk)
            return render(request, self.template_name, {'cliente': cliente})
        except Cliente.DoesNotExist:
            raise Http404("Cliente não encontrado")
    
    def post(self, request ,pk):
        try:
            cliente = Cliente.objects.get(pk=pk)
            cliente.endereco.delete()
            cliente.user.delete()
            cliente.delete()
            return redirect(reverse_lazy('cliente_list'))
        except Cliente.DoesNotExist:
            raise Http404("Cliente não encontrado")               
    
class PizzaDeleteView(DeleteView):
    model = Pizza
    template_name = 'cadastros/pizza_delete.html'
    success_url = reverse_lazy('pizza_list')

cavernadapizza/cadastros/templates/listas/cliente_list.html
{% extends "cadastros/modelo.html" %}

{% block conteudo %}
  <br>
  <h2>Lista de Clientes Registrados</h2>
  <td>
  <a href="{% url 'cliente_create' %}" class="btn btn-primary btn-sm">Adicionar Cliente</a>
  </td>
  <hr>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
	<tr>
	  <th scope="col">Nome</th>
	 <th scope="col">Opções</th>
	</tr>
      </thead>
      <tbody>
	{% for cliente in object_list %}
	  <tr>
	    <td>{{ cliente }}</td>
	    <td><a href="{% url 'cliente_update' cliente.pk %}" class="btn btn-warning btn-sm">Editar</a> - <a href="{% url 'cliente_delete' cliente.pk %}" class="btn btn-danger btn-sm">Excluir</a></td>
	  </tr>
	{% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

{% block footer %}

{% endblock %}

cavernadapizza/cadastros/templates/listas/pedido_list.html
{% extends 'cadastros/modelo.html' %}

{% load static %}

{% block conteudo %}
<br>
<h3>Lista de Pedidos</h3>
<hr>
<table class="table">
  <thead>
    <tr>
      <th>ID do Pedido</th>
      <th>Data e Hora</th>
      <th>Cliente</th>
      <th>Valor Total (R$)</th>
      <th>Tipo de Pagamento</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for pedido in pedidos %}
    <tr>
      <td>{{ pedido.id }}</td>
      <td>{{ pedido.data_hora }}</td>
      <td>{{ pedido.cliente.nome }}</td>
      <td>{{ pedido.valor_total }}</td>
      <td>{{ pedido.get_tipo_pagamento_display }}</td>
      <td>
        <!--
        <a href="#" class="btn btn-info">Detalhes</a> -->

        <button type="button" class="btn btn-info btn-sm" data-bs-toggle="modal"
          data-bs-target="#staticBackdrop{{ pedido.id }}">Detalhes</button>
        <!--Modal-->
        {% for pedido in pedidos %}
        <div class="modal fade" id="staticBackdrop{{ pedido.id }}" tabindex="-1" role="dialog" data-bs-backdrop="static"
          data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel{{ pedido.id }}"
          aria-hidden="true">
          <div class="modal-dialog modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-3" id="staticBackdropLabel{{ pedido.id }}">Detalhes do Pedido - {{ pedido.id }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <h4>Informações do Pedido</h4>
                <p><strong>Data e Hora:</strong> {{ pedido.data_hora }}</p>
                <p><strong>Valor Total:</strong> R$ {{ pedido.valor_total }}</p>
                <p><strong>Tipo de Pagamento:</strong> {{ pedido.tipo_pagamento }}</p>

                <h4>Itens do Pedido</h4>
                <ul>
                  <!-- Lista de itens do pedido associados a este pedido -->
                  {% for item in itens_pedido %}
                  <li>{{ item.tamanho }} (Quantidade: {{ item.quantidade }})</li>
                  {% endfor %}
                </ul>

                <h4>Cliente</h4>
                <p><strong>Nome do Cliente:</strong> {{ pedido.cliente.nome }}</p>
                <p><strong>Email do Cliente:</strong> {{ pedido.cliente.email }}</p>
                <p><strong>Telefone do Cliente:</strong> {{ pedido.cliente.telefone }}</p>               
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>

              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'pedido_create' %}" class="btn btn-primary">Novo Pedido</a>
</div>



{% endblock %}

{% block footer%}

{% endblock %}

cavernadapizza/cadastros/templates/listas/pizza_list.html
{% extends 'cadastros/modelo.html' %}

{% load static %}

{% block conteudo %}
<br>
<h3>Lista de Pizza registradas</h3>
<td>
  <a href="{% url 'pizza_create' %}" class="btn btn-primary btn-sm">Adicionar Pizza</a>
</td>
<hr>
<div class="table-responsive">
    <table class="table table-striped">
        <tr>
            <th>Nome</th>
            <th>Pequena</th>
            <th>Média</th>
            <th>Grande</th>
            <th>Descrição</th>
            <th>Opções</th>
        </tr>
        {% for pizza in object_list %}
        <tr>
            <td>{{ pizza.nome }}</td>
            <td>{{ pizza.valor_p }}</td>
            <td>{{ pizza.valor_m }}</td>
            <td>{{ pizza.valor_g }}</td>
            <td>{{ pizza.descricao }}</td>            
            <td>
                <a href="{% url 'pizza_update' pizza.pk %}" class="btn btn-warning btn-sm">Editar</i></a>
		<a href="{% url 'pizza_delete' pizza.pk %}" class="btn btn-danger btn-sm">Excluir</a>
            </td>
        </tr>

        {% empty %}
        <tr>
            <td colspan="6"><strong><h6>Nenhum campo registrado</h6></strong></td>
        </tr>
        {% endfor %}

    </table>
</div>

{% endblock %}

{% block footer%}

{% endblock %}